var searchData=
[
  ['datestring',['dateString',['../interface_person_order_info.html#a06083bcc27455fd375fc23a3d64e7d7c',1,'PersonOrderInfo']]],
  ['defaultdatawithbundlename_3a',['defaultDataWithBundleName:',['../interface_bundle_default.html#a5c41dae1e8d22deebcf44836e9762d07',1,'BundleDefault']]],
  ['delegate',['delegate',['../interface_save_operation.html#a06e858b966f4425529f0f47cfa7ae86a',1,'SaveOperation']]],
  ['delivery',['delivery',['../interface_store_item.html#a3ec7d79f007e901d4f08e0dc9b6ccf49',1,'StoreItem']]],
  ['deliverycity',['DeliveryCity',['../interface_delivery_city.html',1,'']]],
  ['deliverycityentity',['DeliveryCityEntity',['../interface_delivery_city_entity.html',1,'']]],
  ['deliverycityentity_28coredatageneratedaccessors_29',['DeliveryCityEntity(CoreDataGeneratedAccessors)',['../category_delivery_city_entity_07_core_data_generated_accessors_08.html',1,'']]],
  ['deliverycomment',['deliveryComment',['../interface_person_order_info.html#a17849aa4153445c1583cbd3bcc1041eb',1,'PersonOrderInfo']]],
  ['deliverymemberentity',['DeliveryMemberEntity',['../interface_delivery_member_entity.html',1,'']]],
  ['deliverystrategy',['DeliveryStrategy',['../interface_delivery_strategy.html',1,'']]],
  ['deliverytype',['DeliveryType',['../interface_delivery_type.html',1,'']]],
  ['deliverytypeentity',['DeliveryTypeEntity',['../interface_delivery_type_entity.html',1,'']]],
  ['deliverytypeentity_28coredatageneratedaccessors_29',['DeliveryTypeEntity(CoreDataGeneratedAccessors)',['../category_delivery_type_entity_07_core_data_generated_accessors_08.html',1,'']]],
  ['descriptionorder',['descriptionOrder',['../interface_item_info_order.html#a216fc6d5f8613fe09cf1bd42c5141f76',1,'ItemInfoOrder']]],
  ['descriptionstore',['descriptionStore',['../interface_store_item.html#aebf514816d86aa9487285da02ecfee2d',1,'StoreItem']]],
  ['devicemanager',['DeviceManager',['../interface_device_manager.html',1,'']]],
  ['downloadimages',['downloadImages',['../interface_template.html#af9796d045865cf02f4447f3585b60819',1,'Template']]],
  ['drawgridview',['DrawGridView',['../interface_draw_grid_view.html',1,'']]],
  ['drawgridview_28_29',['DrawGridView()',['../category_draw_grid_view_07_08.html',1,'']]]
];
