.TH "AppDelegate" 3 "Пн 27 Июл 2015" "Version 1.7 (17)" "PhotoHouse1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:UIResponder и <UIApplicationDelegate>\&.
.SS "Свойства"

.in +1c
.ti -1c
.RI "UIWindow * \fBwindow\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для PhotoHouse1 из исходного текста\&.
