.TH "/Users/diman/Yandex.Disk/projects_xcode/project_xcode_Simple/DoxygenTest/DoxygenTest/Student.h" 3 "Пн 27 Июл 2015" "Version 1.7 (17)" "PhotoHouse1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/diman/Yandex.Disk/projects_xcode/project_xcode_Simple/DoxygenTest/DoxygenTest/Student.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для PhotoHouse1 из исходного текста\&.
