.TH "/Users/diman/Yandex.Disk/projects_xcode/project_xcode_Simple/DoxygenTest/DoxygenTest/ViewController.h" 3 "Пн 27 Июл 2015" "Version 1.7 (17)" "PhotoHouse1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/diman/Yandex.Disk/projects_xcode/project_xcode_Simple/DoxygenTest/DoxygenTest/ViewController.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBViewController\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для PhotoHouse1 из исходного текста\&.
